name: dart_snmp
description: A dart library for communicating with simple network management protocol (snmp) enabled devices
version: 1.0.2-dev
homepage: https://github.com/point-source/dart_snmp
repository: https://github.com/point-source/dart_snmp
issue_tracker: https://github.com/point-source/dart_snmp/issues

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  logging: ^0.11.4
  asn1lib: ^0.8.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
